apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vault
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vault
    spec:
      containers:
      - env:
        - name: ServerIP
          value: 192.168.161.104
        - name: WEBPASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: vault-webpassword
        image: vault
        env:
        - name: VAULT_ADDR
          value: 'http://127.0.0.1:8200'
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: ansible
        imagePullPolicy: IfNotPresent
        name: vault
        ports:
        - containerPort: 8200
          name: vault-http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/vault
          name: config
        - mountPath: /etc/dnsmasq.d/02-custom.conf
          name: custom-dnsmasq
          subPath: 02-custom.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: vault-config
      - configMap:
          defaultMode: 420
          name: vault-custom-dnsmasq
        name: custom-dnsmasq
status: {}
